version: "3"
# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: amirpourmand/al-folio
    container_name: shaozhang.info
    command: bash -c "
      rm -f Gemfile.lock
      && bundler exec jekyll serve --watch --port=60066 --host=0.0.0.0 --livereload --verbose --trace"
    ports:
      - 60066:60066
    volumes:
      - .:/srv/jekyll